#!/usr/bin/env bash
# shellcheck disable=SC1090

set -o errexit
set -o nounset
set -o pipefail
[[ -n "${XTRACE:+x}" ]] && set -o xtrace
[[ -n "${VERBOSE:+x}" ]] && set -o verbose
[[ -n "${DEBUG:-}" ]] && IS_DEBUG=true || IS_DEBUG=false
[[ $- =~ [x] ]] && PS4='+[${BASH_SOURCE}:${LINENO}:${FUNCNAME[0]:+${FUNCNAME[0]}}()]: '

readonly branch=gh-pages
readonly timestamp=$(/bin/date +"%Y%m%d_%H%M%S")

if [[ -z ${SKIP_BUILD:-} ]]; then
  rm -rf build
  npm run build
fi

cp -f .gitignore LICENSE NOTICE README.md build/
cd build
git init .
git remote add origin git@github.com:adoyle-h/design-grid-system.git
git checkout --orphan $branch
git add -f .
git commit -m "Github page generated at ${timestamp}"
git push -f origin $branch
